main:
  params: [input]
  steps:
    - run_job:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: namespaces/policyengine-api-prototype/jobs/simulate-job
          location: us-central1
          body:
            apiVersion: "run.googleapis.com/v1"
            kind: "Job"
            metadata:
              name: simulate-job
            spec:
              template:
                spec:
                  template:
                    spec:
                      containers:
                      - args: 
                          - "{{ input.parameters }}"