main:
  params: [input]
  steps:
    - init:
        assign:
          - projectId: "{{ PROJECT_ID }}"
          - region: "{{ REGION }}"
          - jobName: "simulate-job"
    - run_job:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: namespaces/{{ projectId }}/jobs/{{ jobName }}
          location: {{ region }}
          body:
            apiVersion: "run.googleapis.com/v1"
            kind: "Job"
            metadata:
              name: "{{ jobName }}"
            spec:
              template:
                spec:
                  template:
                    spec:
                      containers:
                      - args: 
                          - "{{ input.parameters }}"