main:
  params: [input]
  steps:
    - run_job:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: namespaces/policyengine-api-prototype/jobs/simulate-job
          location: us-central1
          body:
            overrides:
              containerOverrides:
                env:
                  - name: JOB_ID
                    value: ${input.job_id}
    - run_function:
      call: http.get
      args:
          url: https://us-central1-policyengine-api-prototype.cloudfunctions.net/simulate-function
          query:
            job_id: ${input.job_id}
    