name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Cloud Run Job
        run: |
          gcloud beta run jobs deploy simulate-job \
            --source . \
            --region $REGION \
            --platform managed \
            --project $PROJECT_ID

      - name: Deploy Workflow
        run: |
          gcloud workflows deploy simulate-workflow \
            --source=workflow.yaml \
            --location=$REGION \
            --project $PROJECT_ID